option('gdk-pixbuf', type: 'feature', value: 'auto', description: 'Enable support for more image formats')

option('avif', type: 'feature', value: 'auto', description: 'HDR10 AVIF wallpapers via libavif')
option('jxl', type: 'feature', value: 'auto', description: 'HDR10 JPEG XL wallpapers via libjxl')
